### PR TITLE
New Mods in Firebase Realtime Database and fixes in RegisterScreen

### PR DESCRIPTION
**Pull request by seifibrahim32**
## Checklist

- [X] ✅ My code follows the code style of this project.
- [X] 📝 My change requires a change to the documentation.
- [X] 🎀 I have updated the documentation accordingly.
- [X] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [X] ✨ I have added tests to cover my changes.
- [X] 🚩 All new and existing tests passed.
- [X] 🌟 Fixed the repo

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Screenshot_20220523-164016

Screenshot_20220523-163239

Screenshot_20220523-163218

### CODE REVIEW

**Comment by seifibrahim32** [comment]
@Lakhankumawat @RISING-CODER777 @chandan0000 Kindly mentors , review those as all the issues fixed

**Comment by chandan0000** [comment]
Screenshot_20220529-175949
 Sign in after It is not giving and see sign-up page also once.

**Comment by seifibrahim32** [comment]
Fixed all the bugs reviewers

**Comment by RISING-CODER777** [comment]
@seifibrahim32  @chandan0000  it's working fine and previous issues were resolved and I didn't faced any issue! But there is a little bit delay in signup check it out once!

**Comment by seifibrahim32** [comment]
Fixed ...

**Comment by seifibrahim32** [comment]
@RISING-CODER777 ?? Kindly check again , I hope to merge and check also the .info file the opened PR request.

**Comment by Lakhankumawat** [comment]
Please resolve merge conflicts .

**Comment by chandan0000** [comment]
image
@seifibrahim32 Please resolve merge conflicts .

**Review by Lakhankumawat — APPROVED** [review]
## LGTM ✨🎉

Hopefully merging  this won't crash CI/CD 😅

**Pull request merged**
