### PR TITLE
Smart Home with Firebase added  (CLI Actions improved)

### PR DESCRIPTION
**Pull request by seifibrahim32**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )

## Proposed Changes
- Firebase backend add [Authentication , FirebaseFirestore, Firebase Storage]
- Expected to have Realtime Database

## Additional Info
- Currently Working on ESP microcontroller interfacing .
- HTTP call for weather detection

### CODE REVIEW

**Comment by seifibrahim32** [comment]
Check again but there is still mods on this.....

**Comment by seifibrahim32** [comment]
Done ,@lakhan

**Comment by seifibrahim32** [comment]
?? Lakhan , whats up

**Comment by Lakhankumawat** [comment]
@RISING-CODER777 @chandan0000  please review this PR

**Comment by Lakhankumawat** [comment]
@seifibrahim32  you need to add working screenshots of your changes in PR description , you can edit pr description by clicking three dots in corner .

**Comment by seifibrahim32** [comment]
I will make it within days

**Comment by chandan0000** [comment]
@seifibrahim32  share screenshot please and video

**Comment by Lakhankumawat** [comment]
No response from contributor , this pr will be closed if such conditions are present .

**Comment by chandan0000** [comment]
@seifibrahim32  plz Please share work sreenshot

**Comment by Lakhankumawat** [comment]
TOO many Merge Conflicts  😢, Closing now

**Pull request closed without merging**
