### PR TITLE
New FireStore login and Auth

### PR DESCRIPTION
**Pull request by seifibrahim32**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )

## Proposed Changes
- Change 1
- Change 2

## Additional Info
- Any additional information or context

## Checklist

- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Review by seifibrahim32 — COMMENTED** [review]
Added new view_model, 
new user_model to recall ESP microcontroller

**Review by seifibrahim32 — COMMENTED** [review]
See changes @Lakhankumawat @lakhankumawat01

**Review by seifibrahim32 — COMMENTED** [review]
new firebase changes

**Comment by chandan0000** [comment]
@seifibrahim32 resolve conflict 
Screenshot_20220513-081145_Chrome

**Comment by seifibrahim32** [comment]
how so , please @chandan0000

**Pull request closed without merging**
