### PR TITLE
#6 about page

### PR DESCRIPTION
**Pull request by nrd26**
## Related Issue
- #6 

## Proposed Changes
- About App / App Design / App Architechture
- App Idea and Application
- App Source Code Link
- About Page for developers
- Must include about developers link to github profile opening in browser

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

Created the page according to the figma design

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | 
| ----------- | 
| About Us Page  | 
| Screenshot_1648668674|

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Go to builds and check what caused the build failing ...

**Comment by Lakhankumawat** [comment]
@nrd26  make sure you have **liniting** enabled for flutter in your ide and i would recommend you to resolve the conflicts in your pr 
```
info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:27:41 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:31:50 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:35:24 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:38:58 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:51:20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:58:[18](https://github.com/Lakhankumawat/smart-home-app/runs/5799204294?check_suite_focus=true#step:6:18) • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:70:[20](https://github.com/Lakhankumawat/smart-home-app/runs/5799204294?check_suite_focus=true#step:6:20) • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:77:20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:88:20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:96:20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:107:20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:1[25](https://github.com/Lakhankumawat/smart-home-app/runs/5799204294?check_suite_focus=true#step:6:25):20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:132:20 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:143:46 • unnecessary_const
   info • Avoid const keyword • lib/src/screens/about_screen/about_us_screen.dart:149:42 • unnecessary_const

```

**Comment by Lakhankumawat** [comment]
If you are unsure or issue still persisits then raise your doubt in project discord general and i will try to solve your doubt on a live stream , but make sure  give it your try and research on it first .

**Comment by chandan0000** [comment]
Screenshot_20220412-152252_Chrome
Fix it

**Comment by Lakhankumawat** [comment]
@nrd26  Any Updates ?

**Comment by nrd26** [comment]
My apologies for the delay @Lakhankumawat @chandan0000 . I was held up with college exams. I believe my last pr has resolved the problem

**Comment by Lakhankumawat** [comment]
Will review and merge your PR soon if everything seems awesome , meanwhile you can get hold of other issues , keep learning keep contributing ✨

**Comment by Lakhankumawat** [comment]
> Will review and merge your PR soon if everything seems awesome , meanwhile you can get hold of other issues , keep learning keep contributing ✨

@chandan0000  please review the PR

**Review by Lakhankumawat — APPROVED** [review]
LGTM ✨🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @nrd26 code ,

**Pull request merged**
