### PR TITLE
Set event screen

### PR DESCRIPTION
**Pull request by Fredorixo**
## Related Issue
- #31

## Proposed Changes
- Added an ElevatedButton in home_screen/components/body.dart
- SetEventScreen.routeName added to routes.dart
- table_calendar dependency in pubspec.yaml
- ABeeZee font files in the fonts directory and in pubspec file
- Added TextSelectionTheme to main.dart
- Custom Theme files inside the set_event_screen directory
- Components directory consisting of event.dart and event_list_tile.dart
- A resources.dart file for exporting a bunch of files

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Screen View | Alert Dialogs |
|image|image|
|image|image|

### CODE REVIEW

**Comment by chandan0000** [comment]
@Fredorixo  and needs to be fixed. It is not complete. Your ui 
You goto figma file fthen fix it

**Comment by chandan0000** [comment]
Get it fixed as soon as possible and your pr is now ready to merge.

**Comment by Fredorixo** [comment]
Will you please mention the area of correction, precisely.

**Comment by Lakhankumawat** [comment]
Ok i'll mention you more specifically what you exactly need to be doing , you in  discord ?

**Comment by Lakhankumawat** [comment]
image


Follow this Pop Up styles in your DESIGN and you can find them in figma you can beautify the designs as you like but make too many chnages in design

**Comment by Lakhankumawat** [comment]
At last few doubts 
1. Are you a GSSoC22 contributor?
2. Are you in discord ?
3. Are you in project channel inside discord ?

**Comment by Fredorixo** [comment]
Yes, I'm a contributor of GSSoC22 and a part of the project channel in discord too

**Comment by Fredorixo** [comment]
The UI Design has been updated to

image

**Comment by Lakhankumawat** [comment]
1. Not modified PopUps yet 
2. make the button `+ Add New Event ` screen width responsive
3. Divide your widgets into small stateless components if possible
4. instead of having theme folder inside set events **create a components folder just like other screen folders**

**Comment by Lakhankumawat** [comment]
resolve the conflicts please then i will merge it .

**Comment by Fredorixo** [comment]
> resolve the conflicts please then i will merge it .

Resolved the conflicts, used the popups in the design and made the width of `add button` responsive

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🎉✨

**Pull request merged**
