### PR TITLE
fixed overflow on energy saving card

### PR DESCRIPTION
**Pull request by Pavel401**
## Related Issue
#49 
## Proposed Changes
-fixed overflow 

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
Before            |  After
:-------------------------:|:-------------------------:
WhatsApp Image 2022-03-30 at 1 50 06 PM|WhatsApp Image 2022-03-30 at 1 50 06 PM (1)

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
## Starr the REPO please

**Comment by Pavel401** [comment]
> ## Starr the REPO please

Done

**Review by chandan0000 — APPROVED** [review]
> ## Thank you for contributing like this, keep doing such contributing in future also 🎉

**Comment by Lakhankumawat** [comment]
LGTM 🎉✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Pavel401  code

**Pull request merged**
