### PR TITLE
IoT For ESP8266 with Firebase

### PR DESCRIPTION
**Pull request by seifibrahim32**
## Related Issue
- IoT Firebase for callbacks for Flutter Application .
## Proposed Changes
-  Merging the file for future usages

## Breadboard configurations
- https://www.youtube.com/watch?v=e9GzZ7-rOnc
- Be sure you defined the port on Arduino IDE.
- Be sure that you choose Anonymous on Firebase not just only email and password
- Another video sample : https://www.youtube.com/watch?v=-CX2kbgNCxA   (from me myself.)
 

## What does this file do?
- The IoT helps in smart home applications , as ESP8266 is a microcontroller helps in getting WiFi SSID request either input or output.
- I used Arduino IDE as a method for making any code to provide the microcontroller more functionality.
- Once I clicked on button it stored in the RealTime Database that is on and vice versa.
- In arduino There is a ready file for Firebase as it authenticates the username and password that exists in the cloud, and 
- Setup function : function used to configure the installation of the wires connection on the breadboard AND THE WIFI configurations if there is a user connected to the internet and ip address is valid, while the loop is used to make any input or output functions and the loops many times to, during the loop it takes the information from realtime database it stores on the ESP microcontroller and the data prints on LCD.

### CODE REVIEW

**Comment by seifibrahim32** [comment]
@Lakhankumawat @lakhankumawat01 IoT only ... the another edits on the other once updated i will inform you

**Comment by seifibrahim32** [comment]
@Lakhankumawat @chandan0000 @RISING-CODER777 kindly review those

**Comment by seifibrahim32** [comment]
@RISING-CODER777 see this ? ino file

**Review by Lakhankumawat — APPROVED** [review]
## LGTM 🌟🍩☕

**Comment by Lakhankumawat** [comment]
@all-contributors please add @seifibrahim32  code ,

**Pull request merged**
