### PR TITLE
Edit profile

### PR DESCRIPTION
**Pull request by VrishtiGupta11**
## Related Issue
- #19 

## Proposed Changes
- Added Iconbutton in home_screen.dart.
- Route added in routes.dart.
- edit_profile.dart in edit_profile/
- body.dart in edit_profile/components/
- image_picker.dart in edit_profile/components/
- Added image_picker dependency in pubspec.yaml

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Edit Profile Page  | Edit Profile Page     |
|   |      |

## Demo

https://user-images.githubusercontent.com/53931644/158020284-1f08c74f-5580-4774-ab9c-f364ea856e8c.mp4

### CODE REVIEW

**Review by Lakhankumawat — COMMENTED** [review]
Your Code Looks Good

**Comment by Lakhankumawat** [comment]
Resolve the issue which are failing this checks.

**Comment by chandan0000** [comment]
LGMT

**Comment by chandan0000** [comment]
@VrishtiGupta11  Something error has come, update it. Your PR will soon be merged.

**Comment by VrishtiGupta11** [comment]
Could you please guide about how can I resolve this issue? Do I need to add more commits to edit-profile branch?

**Comment by Lakhankumawat** [comment]
Once everything seems good we will merge your Pr for sure ✅

**Comment by Lakhankumawat** [comment]
@all-contributors please add @VrishtiGupta11  code ,

**Pull request merged**
