### PR TITLE
Replaced Some Deprecated properties with new one

### PR DESCRIPTION
**Pull request by harsh082ip**
## Related Issue
- There were some deprecated properties which I replaced

## Proposed Changes
- Change 1 (Replaced deprecated properties like headline1, headline2, bodyText1, etc with new one)
- Change 2 (.vscode/settings.json removed)

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by harsh082ip** [comment]
Hii, I'm facing problem in building the apk in my local system, even when I forked it
I have made the necessary changes, but not able to build the apk,
when i forked it I tried every possible way, but can't get through What is the error, why it is not working, I have replaced the deprecated properties with new one, but on pushing the code, I wasn't able to create a successful pull request because the build apk part failed, rest all are passed
I make sure that I haven't made any change in build.gradle file or any build file, I have just made the changes in the dart file and replaced the deprecated properties with the new one
I would be very glad😊 if you please help me regarding this
I have attached the error code snippet 
build

**Comment by Lakhankumawat** [comment]
If flutter CI passes then i'll merge this request.

**Comment by Lakhankumawat** [comment]
builds are still failing .

**Comment by harsh082ip** [comment]
I'm trying my level best if CI passes please merge it, 
Thank you

**Comment by Lakhankumawat** [comment]
I've made the required changes and the issue is gone, closing the PR.

**Pull request closed without merging**
