### PR TITLE
Added Menu Page

### PR DESCRIPTION
**Pull request by Chitrakshi2531**
## Related Issue
#13 

## Proposed Changes
- Added icons in assets/menu_icons/
- Added drawer in home_screen.dart
- menu_page.dart in menu_page/
- body.dart , menu_list.dart , list_tile.dart in menu_page/components

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [x] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      |
| ----------- | 
| Menu Page |
|menu page  | 
 
## Demo
              

https://user-images.githubusercontent.com/99464268/160296575-e1e226d3-fbf9-4622-a056-308fe79e1e4a.mp4

### CODE REVIEW

**Comment by chandan0000** [comment]
Screenshot_20220328-042847_Chrome
Fix this issue @Chitrakshi2531

**Comment by Lakhankumawat** [comment]
Wrap your settings inside inkwell so that when user press on button he/she can see a splash animation 

just like the image below when you hold on warm button


Screenshot_20220328-153326

**Comment by Chitrakshi2531** [comment]
https://user-images.githubusercontent.com/99464268/160441873-1d0569df-199a-462e-a51d-d9f0f795b230.mp4

**Review by Lakhankumawat — APPROVED** [review]
@chandan0000  please verify check code quality and conventions Design LGTM 💯🌟

**Review by chandan0000 — APPROVED** [review]
# Thanks 
## Keep doing this kind of contribution in future also

**Comment by chandan0000** [comment]
your pr is soon merged

**Review by Lakhankumawat — APPROVED** [review]
LGTM 🌟💯

**Pull request merged**
