### PR TITLE
[Feature] Add Profile Screen #8

### PR DESCRIPTION
**Pull request by Ashish-AI**
## Related Issue
- #8
## Proposed Changes
- Add Profile Landing screen 
- Remove unused imports for few file 
- Add SVGs (icons)

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1    |
| ----------- | ----------- |
| Profile Landing Sreen  |
Screenshot_2022-03-05-22-36-36-43_156b98136834c1c0c80dbf8c5346c3f4

### CODE REVIEW

**Comment by chandan0000** [comment]
@Ashish-AI  improve your design then make a video

**Comment by Ashish-AI** [comment]
@chandan0000  What kind of changes do you want in the UI?

**Comment by chandan0000** [comment]
Icons and font size is not comfortable and padding and margin issue

**Comment by Ashish-AI** [comment]
font size can appear different because of the fact that we are using a different font than what we are using on figma. Rest everything is designed as per Figma. 
The function dedicated to handling the responsiveness is not giving the expected output. So some adjustments are made by reducing the size.

**Pull request closed without merging**
