### PR TITLE
schedule in lightening screen widget overflow #29

### PR DESCRIPTION
**Pull request by mariam199911**
## Related Issue
- #29 

## Proposed Changes
-  panel to panelBuilder
- column in  ExpandableBottomSheet to ListView

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [x] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
image

| Title goes here  | Title goes here     |
| Image goes here  | Image goes here     |

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Please show me the screenshot for overflow then i will see your code and everything

**Comment by Lakhankumawat** [comment]
show what changes you have done a , before and after , then just pasting a screenshot , with which no one come to know what acually changes you have made in ui , because there was no overflow issue on device i expect some ss related to overflow

**Comment by mariam199911** [comment]
image

**Comment by Lakhankumawat** [comment]
@all-contributors please add @mariam199911  code ,

**Comment by Lakhankumawat** [comment]
close

**Comment by Lakhankumawat** [comment]
close #29

**Pull request merged**
