### PR TITLE
Popups

### PR DESCRIPTION
**Pull request by Fredorixo**
## Related Issue
- #42

## Proposed Changes
- All the proposed changes go into popups directory in lib.
- Added Lexend font files to assets and pubspec.
- Created popup_widgets directory containing all the custom made widgets, and the remaining implementational files (the ones that make use of popup_widgets) are directly associated with popups.

## Additional Info
- This design is implemented as a multi purpose design that can be used be as part of other screens that make use of alert dialogs.

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot |
| ----------- |
| Various Popup Designs |
| image|

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
How do we access popoups from app you should have made some dummy buttons in some corner which could have been removed later , cause we check build first then code .

**Comment by Fredorixo** [comment]
> How do we access popoups from app you should have made some dummy buttons in some corner which could have been removed later , cause we check build first then code .

I've added the button

**Review by Lakhankumawat — COMMENTED** [review]
@chandan0000  please review the code

**Comment by Lakhankumawat** [comment]
Design LGTM 🎉🌟

**Comment by Lakhankumawat** [comment]
@all-contributors please add @Fredorixo  code ,

**Pull request merged**
