### PR TITLE
smart fan screen made

### PR DESCRIPTION
**Pull request by HetviSoni**
## Related Issue -#15
Demo:

https://user-images.githubusercontent.com/76479104/156616242-c9e369c9-e9ff-473d-8a9b-dd6ee83b4b4a.mp4

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
Check this checklists whichever apply to your contribution


## Checklist



- [ ] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [ ] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

**Comment by HetviSoni** [comment]
As mentioned in issue #15 i have made the smart_fan screen.
Files added: (location)
**smart_fan (directory)**  : smart-home-app/lib/src/screens/
**components** (directory) : smart-home-app/lib/src/screens/smart_fan/
**body.dart** : smart-home-app/lib/src/screens/smart_fan/components/
**expandable_bottom_sheet.dart** : app/lib/src/screens/smart_fan/components/
**smart_fan.dart** :  app/lib/src/screens/smart_fan/

The JSON file for Lottie animation is added inside the Lottie folder in assets.

Checklist.
&#9745; My code follows the code style of this project.
&#9744; My change requires a change to the documentation.
&#9744; I have updated the documentation accordingly.
&#9745;I have read the [CONTRIBUTING](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
&#9744; I have added tests to cover my changes.
&#9744;All new and existing tests passed.
&#9745; starred ed the repo

**Comment by Lakhankumawat** [comment]
@WarMac4964  please review this

**Comment by chandan0000** [comment]
LGTM

**Review by chandan0000 — APPROVED** [review]

**Comment by Lakhankumawat** [comment]
Great Work @HetviSoni  🎉🎉

**Comment by Lakhankumawat** [comment]
@all-contributors please add @HetviSoni  code ,

**Comment by HetviSoni** [comment]
> Great Work @HetviSoni 🎉🎉

Thank you😇

**Comment by chandan0000** [comment]
@HetviSoni  welcome to Smart home family 

We want to continue doing this kind of contribution in future also

**Pull request merged**
