### PR TITLE
Added Login Screen

### PR DESCRIPTION
**Pull request by RanchoDbest**
## Related Issue
- Mention issue for which this pull request is a part of (please mention issue number # )

## Proposed Changes
- Change 1
- Chnage 2

## Additional Info
- Any additional information or context

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [ ] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| Title goes here  | Title goes here     |
Screenshot 2022-03-24 at 4 41 37 PM

| Image goes here  | Image goes here     ||

### CODE REVIEW

**Comment by RanchoDbest** [comment]
I have resolved issues, please review it.

**Review by Lakhankumawat — APPROVED** [review]
LGTM 💯✨

**Comment by Lakhankumawat** [comment]
@all-contributors please add @RanchoDbest  code ,

**Comment by Lakhankumawat** [comment]
Great Work @RanchoDbest  ✨✨

**Pull request merged**
