### PR TITLE
added favourites screens

### PR DESCRIPTION
**Pull request by HetviSoni**
## Proposed Changes
- Added favourites screen with empty list and "add to favourites" option
- Added favourites screen with list of all favourite items.

## Output Screenshots
| Screenshot #1      | Screenshot #2  |
| ----------- | ----------- |
| when no favourite items  |        Favourite list     |
|| |

## Checklist

- [x] ✅ My code follows the code style of this project.
- [x] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/Lakhankumawat/sort_it/blob/master/Contributing.md) document.
- [ ] ✨ I have added tests to cover my changes.
- [ ] 🚩 All new and existing tests passed.
- [x] 🌟 ed the repo

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Demo Video

https://user-images.githubusercontent.com/76479104/169580844-1105a89e-0f0d-40b6-9f4c-e008fc831f59.mp4

### CODE REVIEW

**Comment by Lakhankumawat** [comment]
IMG_20220522_082220

## this is the design right !?

**Comment by HetviSoni** [comment]
As we are adding devices from home screen to favorites screen ..so what device is the first one in design?

**Comment by chandan0000** [comment]
LGTM

**Review by chandan0000 — APPROVED** [review]

**Comment by Lakhankumawat** [comment]
@RISING-CODER777 please review the Pr

**Comment by Lakhankumawat** [comment]
@all-contributors please add @HetviSoni code

**Pull request merged**
